### ISSUE TITLE
(Wildcard certs) Ingress TLS secrets are not updated because both cert hashes are empty strings

### ISSUE THREAD

**Issue by reloaded** [math-nao/certs#21]
Greetings,

I've deployed this to my minikube cluster running k8s >= 1.16 and using helm3. So far the TLS cert and private key has not been attached to my nginx ingress controller. After digging into this for most of the day I realized it's because the shell script is not saving the certificate and private keys to a k8s TLS secret. 

**Important note, details and logs in this issue are from the first pod that ran immediately after helm deployment..**

My SSL cert is for a wildcard domain name and I'm beginning to wonder if the asterisk in the domain name is causing issues due to shell file system path expansion. Since this is the first time the cert pod ran I'd expect the "current cert hash" to be an empty string/null and the "new cert hash" to contain a hash of the newly issued cert, however they are both empty strings/null.

Here's where the hash conditional check evaluates as false because both hash values are empty string, therefore bypassing functions that save the certs to k8s TLS secrets. 
* https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L282

I also noticed the "domain folder" variables are empty strings, shouldn't they be paths? Perhaps more validation needs to be added to ensure these variables are not empty strings and check if they exist? 
* https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L254
* https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L274

Here is what I think to be the most important logs.

```
Info: Generate certs for  dns: dns_cloudns,  is_staging: true,  is_debug: true,  args: ,  cmd to use: acme.sh --issue --ca-file '/root/certs/ca.crt' --cert-file '/root/certs/tls.crt' --fullchain-file '/root/certs/fullchain.crt' --key-file '/root/certs/tls.key' -d '*.dev.mydomain.com' --staging --dns 'dns_cloudns',  name: ingress-tls-secrets,  namespace: myappnamespace,  domains: 31021.dev.mydomain.com 32010.dev.mydomain.com
Debug: main domain: 31021.dev.mydomain.com
Debug: domain folder: 
Debug: current cert hash: 
Debug: Running cmd: acme.sh --issue --ca-file '/root/certs/ca.crt' --cert-file '/root/certs/tls.crt' --fullchain-file '/root/certs/fullchain.crt' --key-file '/root/certs/tls.key' -d '*.dev.mydomain.com' --staging --dns 'dns_cloudns'
[Wed Feb 26 07:48:29 UTC 2020] Your cert is in  /acme.sh/*.dev.mydomain.com/*.dev.mydomain.com.cer 
[Wed Feb 26 07:48:29 UTC 2020] Your cert key is in  /acme.sh/*.dev.mydomain.com/*.dev.mydomain.com.key 
[Wed Feb 26 07:48:29 UTC 2020] The intermediate CA cert is in  /acme.sh/*.dev.mydomain.com/ca.cer 
[Wed Feb 26 07:48:29 UTC 2020] And the full chain certs is there:  /acme.sh/*.dev.mydomain.com/fullchain.cer 
[Wed Feb 26 07:48:29 UTC 2020] Installing cert to:/root/certs/tls.crt
[Wed Feb 26 07:48:29 UTC 2020] Installing CA to:/root/certs/ca.crt
[Wed Feb 26 07:48:29 UTC 2020] Installing key to:/root/certs/tls.key
[Wed Feb 26 07:48:29 UTC 2020] Installing full chain to:/root/certs/fullchain.crt
Info: acme.sh return code: 0
Debug: domain folder: 
Debug: new cert hash: 
Info: No certificate change, nothing to do
```

**Full log output below with sensitive information redacted.**

```
wait few seconds in case ingress rule is deployed at the same as it is in demo
Info: Initialize environment...
Info: No cmd args found
Info: Generate certs for  dns: dns_cloudns,  is_staging: true,  is_debug: true,  args: ,  cmd to use: acme.sh --issue --ca-file '/root/certs/ca.crt' --cert-file '/root/certs/tls.crt' --fullchain-file '/root/certs/fullchain.crt' --key-file '/root/certs/tls.key' -d '*.dev.mydomain.com' --staging --dns 'dns_cloudns',  name: helm-node-port-ingress-tls-secrets,  namespace: myappnamespace,  domains: 31021.dev.mydomain.com 32010.dev.mydomain.com
Info: Loading conf from secret...
Debug: Status code: 404
Info: Invalid status code found: 404, configuration not loaded
Debug: main domain: 31021.dev.mydomain.com
Debug: domain folder: 
Debug: current cert hash: 
Debug: Running cmd: acme.sh --issue --ca-file '/root/certs/ca.crt' --cert-file '/root/certs/tls.crt' --fullchain-file '/root/certs/fullchain.crt' --key-file '/root/certs/tls.key' -d '*.dev.mydomain.com' --staging --dns 'dns_cloudns'
[Wed Feb 26 07:47:34 UTC 2020] Using stage ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Wed Feb 26 07:47:35 UTC 2020] Create account key ok.
[Wed Feb 26 07:47:35 UTC 2020] Registering account
[Wed Feb 26 07:47:35 UTC 2020] Registered
[Wed Feb 26 07:47:35 UTC 2020] ACCOUNT_THUMBPRINT='cuFlQk1Ew3d853EOrVd'
[Wed Feb 26 07:47:35 UTC 2020] Creating domain key
[Wed Feb 26 07:47:36 UTC 2020] The domain key is here: /acme.sh/*.dev.mydomain.com/*.dev.mydomain.com.key
[Wed Feb 26 07:47:36 UTC 2020] Single domain='*.dev.mydomain.com'
[Wed Feb 26 07:47:36 UTC 2020] Getting domain auth token for each domain
[Wed Feb 26 07:47:36 UTC 2020] Getting webroot for domain='*.dev.mydomain.com'
[Wed Feb 26 07:47:36 UTC 2020] Adding txt value: 02mZ8mkugqZRwQDX8b-QHtJN54 for domain:  _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:47:36 UTC 2020] Using cloudns
[Wed Feb 26 07:47:38 UTC 2020] Adding the TXT record for _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:47:39 UTC 2020] Added.
[Wed Feb 26 07:47:39 UTC 2020] The txt record is added: Success.
[Wed Feb 26 07:47:39 UTC 2020] Let's check each dns records now. Sleep 20 seconds first.
[Wed Feb 26 07:47:59 UTC 2020] Checking dev.mydomain.com for _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:48:00 UTC 2020] Not valid yet, let's wait 10 seconds and check next one.
[Wed Feb 26 07:48:10 UTC 2020] Let's wait 10 seconds and check again.
[Wed Feb 26 07:48:20 UTC 2020] Checking dev.mydomain.com for _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:48:21 UTC 2020] Domain dev.mydomain.com '_acme-challenge.dev.mydomain.com' success.
[Wed Feb 26 07:48:21 UTC 2020] All success, let's return
[Wed Feb 26 07:48:21 UTC 2020] Verifying: *.dev.mydomain.com
[Wed Feb 26 07:48:24 UTC 2020] Success
[Wed Feb 26 07:48:24 UTC 2020] Removing DNS records.
[Wed Feb 26 07:48:24 UTC 2020] Removing txt: 02mZ8mkugqZRwQDX8b-QHtJN54 for domain: _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:48:24 UTC 2020] Using cloudns
[Wed Feb 26 07:48:27 UTC 2020] Deleting the TXT record for _acme-challenge.dev.mydomain.com
[Wed Feb 26 07:48:27 UTC 2020] Deleted.
[Wed Feb 26 07:48:27 UTC 2020] Removed: Success
[Wed Feb 26 07:48:27 UTC 2020] Verify finished, start to sign.
[Wed Feb 26 07:48:27 UTC 2020] Lets finalize the order, Le_OrderFinalize: https://acme-staging-v02.api.letsencrypt.org/acme/finalize/12580894/76749265
[Wed Feb 26 07:48:28 UTC 2020] Download cert, Le_LinkCert: https://acme-staging-v02.api.letsencrypt.org/acme/cert/faabbedb70adc462c37f2
[Wed Feb 26 07:48:29 UTC 2020] Cert success.
-----BEGIN CERTIFICATE-----
MIIFWDCCBECgAwIBAgITAPqrvttwrcRiw38vyXC2qkU90zANBgkqhkiG9w0BAQsF
ADAiMSAwHgYDVQQDDBdGYWtlIExFIEludGVybWVk
...removed for privacy...
-----END CERTIFICATE-----
[Wed Feb 26 07:48:29 UTC 2020] Your cert is in  /acme.sh/*.dev.mydomain.com/*.dev.mydomain.com.cer 
[Wed Feb 26 07:48:29 UTC 2020] Your cert key is in  /acme.sh/*.dev.mydomain.com/*.dev.mydomain.com.key 
[Wed Feb 26 07:48:29 UTC 2020] The intermediate CA cert is in  /acme.sh/*.dev.mydomain.com/ca.cer 
[Wed Feb 26 07:48:29 UTC 2020] And the full chain certs is there:  /acme.sh/*.dev.mydomain.com/fullchain.cer 
[Wed Feb 26 07:48:29 UTC 2020] Installing cert to:/root/certs/tls.crt
[Wed Feb 26 07:48:29 UTC 2020] Installing CA to:/root/certs/ca.crt
[Wed Feb 26 07:48:29 UTC 2020] Installing key to:/root/certs/tls.key
[Wed Feb 26 07:48:29 UTC 2020] Installing full chain to:/root/certs/fullchain.crt
Info: acme.sh return code: 0
Debug: domain folder: 
Debug: new cert hash: 
Info: No certificate change, nothing to do
```

**Comment by reloaded** [comment]
UPDATE:

Alright I confirmed this is a bug that only exists when you're requesting a wildcard cert using `acme.sh --issue ... -d '*.mydomain.com'`

If I remove `-d '*.mydomain.com'` and generate multiple certs instead of one wildcard everything works and the k8s ingress TLS secret is created....

Not sure if this is an issue with acme.sh or `math-nao/certs`

How should we proceed to fix this? @math-nao

**Comment by math-nao** [comment]
Hi @reloaded, this issue is on `math-nao/certs`, it occurs due to the domain argument you added in `acme.kubernetes.io/cmd-to-use` annotation value; it does not match any value declared in `.spec.tls.hosts`.

I updated code on `dev` branch to try to handle this case (not tested). Could you update your values.yaml file to use dev docker image tag and try again?

```
image:
  tag: dev
```

**Comment by reloaded** [comment]
The issue persists.

However now the domain folder string is populated... but the cert hashes are still empty strings. Just a reminder this was the very first run so i'd expect the cert to be installed in the k8s TLS secret.

```
Info: acme.sh return code: 0
Debug: domain folder: *.mydomain.com
Debug: new cert hash: 
Info: No certificate change, nothing to do
```

**Comment by math-nao** [comment]
I did a small change about getting domain folder.
Could you try again?

**Comment by reloaded** [comment]
That did the trick @math-nao  !

When could we get this into master and deploy a new docker image? Would love to integrate the stable image today.

**Comment by math-nao** [comment]
done.
